apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: script
spec:
  steps:
    - name: step-with-script
      image: alpine:3.20
      script: |
        #!/bin/sh
        echo "Step with Script..."
        sed -i "s@https://dl-cdn.alpinelinux.org/@https://mirrors.huaweicloud.com/@g" /etc/apk/repositories
        echo "Installing necessary tooling"
        apk update && apk add curl
        curl -s www.magedu.com &> /dev/null && echo "Success" || echo "Fail" 
        echo "All done!"
