apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pipeline-demo-run-xxxxx
  namespace: default
spec:
  pipelineRef:
    name: pipeline-demo
  serviceAccountName: default
  timeout: 1h0m0s
