apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-with-params
spec:
  params:
    - name: text
      type: string
  tasks:
    - name: task-one
      taskRef:
        name: hello-params
    - name: task-two
      taskRef:
        name: logger
      params:
        - name: text
          value: $(params.text)
