apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache
spec:
  storageClassName: openebs-rwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: source-2-package
spec:
  params:
    - name: git-url
      type: string
  workspaces:
    - name: codebase
  tasks:
    - name: fetch-from-source
      params:
        - name: url
          value: $(params.git-url)
      taskSpec:
        workspaces:
          - name: source
        params:
          - name: url
        steps:
          - name: git-clone
            image: alpine/git:v2.45.2
            script: git clone -v $(params.url) $(workspaces.source.path)/source
      workspaces:
        - name: source
          workspace: codebase
    - name: build-package
      runAfter:
        - fetch-from-source
      taskSpec:
        steps:
          - name: build
            #image: maven:3.8-openjdk-11-slim
            image: maven:3.8.7-eclipse-temurin-11-alpine
            workingDir: $(workspaces.source.path)/source
            volumeMounts:
              - name: m2
                mountPath: /root/.m2
            script: |
              curl -sL https://gitee.com/mageedu/spring-boot-helloWorld/raw/main/maven/settings.xml -o /usr/share/maven/conf/settings.xml
              #cat maven/settings.xml > /usr/share/maven/conf/settings.xml
              mvn clean install
        workspaces:
          - name: source
        volumes:
          - name: m2
            persistentVolumeClaim:
              claimName: maven-cache
      workspaces:
        - name: source
          workspace: codebase
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: source-2-package-run-002
spec:
  pipelineRef:
    name: source-2-package
  params:
    - name: git-url
      value: https://gitee.com/mageedu/spring-boot-helloWorld.git
      #value: http://code.gitlab.svc.cluster.local/root/spring-boot-helloWorld.git
  workspaces:
    - name: codebase
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: openebs-hostpath
