apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: source-to-package
spec:
  params:
  - name: git-repo-url
    type: string
  workspaces:
    - name: source
      description: code storage
  steps:
    - name: fetch-from-source
      image: alpine/git:v2.45.2
      script: |
        git clone $(params.git-repo-url) $(workspaces.source.path)/source
    - name: build-to-package
      image: maven:3.8.7-eclipse-temurin-11-alpine
      workingDir: $(workspaces.source.path)/source
      script: |
        curl -sL https://gitee.com/mageedu/spring-boot-helloWorld/raw/main/maven/settings.xml -o /usr/share/maven/conf/settings.xml
        mvn clean install
      volumeMounts:
        - name: maven-cache
          mountPath: /root/.m2
  volumes:
  - name: maven-cache
    persistentVolumeClaim:
      claimName: maven-cache
