apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-cache-s2i
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-rwx
  volumeMode: Filesystem
