apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: s2i-image-push-run-00001
spec:
  pipelineRef:
    name: source-to-image
  params:
    - name: git-url
      #value: https://gitee.com/mageedu/spring-boot-helloWorld.git
      value: http://code.gitlab.svc.cluster.local/root/spring-boot-helloWorld.git
    - name: image-url
      #value: ikubernetes/spring-boot-helloworld
      value: registry.magedu.com/ikubernetes/spring-boot-helloworld
    - name: image-tag
      value: v0.9.3
  workspaces:
    - name: codebase
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: openebs-hostpath
    - name: docker-config
      secret:
        secretName: registry-credential
