apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: s2i-binding
spec:
  params:
  - name: git-revision
    value: $(body.checkout_sha)
  - name: git-repo-url
    value: $(body.repository.git_http_url)
  - name: image-url
    # value: ikubernetes/spring-boot-helloworld
    value: registry.magedu.com/ikubernetes/spring-boot-helloworld
  - name: version
    value: v0.9
